# Generated by Django 2.1.8 on 2019-11-04 22:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('number', models.IntegerField()),
                ('production', models.DateTimeField()),
                ('safe_date', models.CharField(max_length=32)),
                ('picture', models.ImageField(default='shop/img/gougou.png', upload_to='shop/img')),
                ('description', ckeditor.fields.RichTextField()),
                ('statue', models.IntegerField(default=1)),
                ('good_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QUser.User')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('picture', models.ImageField(default='shop/img/gougou.png', upload_to='shop/img')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.GoodsType'),
        ),
    ]
