# Generated by Django 2.1.8 on 2019-10-29 01:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('number', models.ImageField(upload_to='')),
                ('production', models.DateTimeField()),
                ('safe_data', models.CharField(max_length=32)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
