# Generated by Django 2.1.8 on 2019-10-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='safe_data',
            new_name='safe_date',
        ),
        migrations.AddField(
            model_name='goods',
            name='statue',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
