# Generated by Django 2.1.8 on 2019-11-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='production',
            field=models.TextField(),
        ),
    ]
