# Generated by Django 2.1.8 on 2019-10-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_auto_20191029_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(default='shop/img/gougou.png', upload_to='shop/img'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='statue',
            field=models.IntegerField(default=0),
        ),
    ]
