# Generated by Django 2.1.8 on 2019-10-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_auto_20191029_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='statue',
            field=models.IntegerField(default=1),
        ),
    ]
