# Generated by Django 2.1.8 on 2019-10-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_auto_20191029_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='number',
            field=models.IntegerField(),
        ),
    ]
