# Generated by Django 2.1.8 on 2019-10-30 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_goodstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Shop.GoodsType'),
            preserve_default=False,
        ),
    ]
