# Generated by Django 2.1.8 on 2019-10-31 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QUser', '0010_user_identity'),
        ('Shop', '0009_goods_goods_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='good_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='QUser.User'),
            preserve_default=False,
        ),
    ]
