# Generated by Django 2.1.8 on 2019-11-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recver', models.CharField(max_length=64)),
                ('address', models.TextField()),
                ('post_number', models.CharField(max_length=32)),
                ('phono', models.CharField(max_length=32)),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=32)),
                ('goods_id', models.IntegerField()),
                ('goods_name', models.TextField()),
                ('goods_price', models.TextField()),
                ('goods_picture', models.TextField()),
            ],
        ),
    ]
