# Generated by Django 2.1.8 on 2019-11-05 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QUser', '0002_goodsaddress_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsaddress',
            old_name='phono',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='goodsaddress',
            name='goodsaddress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='QUser.User'),
            preserve_default=False,
        ),
    ]
