# Generated by Django 2.1.8 on 2019-11-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QUser', '0003_auto_20191105_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsaddress',
            old_name='goodsaddress',
            new_name='user',
        ),
    ]
