# Generated by Django 2.1.8 on 2019-10-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QUser', '0003_auto_20191028_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=0, max_length=4, null=True),
        ),
    ]
