# Generated by Django 2.1.8 on 2019-10-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QUser', '0005_auto_20191028_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='shop/img/gougou.png', upload_to='shop/img'),
        ),
    ]
