# Generated by Django 2.1.8 on 2019-10-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QUser', '0006_auto_20191029_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='images/gougou.png', upload_to='images'),
        ),
    ]
