# Generated by Django 2.1.8 on 2019-10-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QUser', '0007_auto_20191029_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, max_length=32, null=True),
        ),
    ]
