# Generated by Django 2.1.8 on 2019-10-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QUser', '0009_auto_20191029_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.IntegerField(default=0),
        ),
    ]
